-- Seed 100 Premier League player names (mix of historic legends and current stars).
-- Idempotent via the unique (name, category) constraint from 0001_init.sql.

insert into football_players (name, category) values
  ('Steven Gerrard', 'premier-league'),
  ('Frank Lampard', 'premier-league'),
  ('John Terry', 'premier-league'),
  ('Rio Ferdinand', 'premier-league'),
  ('Wayne Rooney', 'premier-league'),
  ('Cristiano Ronaldo', 'premier-league'),
  ('Thierry Henry', 'premier-league'),
  ('Patrick Vieira', 'premier-league'),
  ('Dennis Bergkamp', 'premier-league'),
  ('Robert Pires', 'premier-league'),
  ('Eric Cantona', 'premier-league'),
  ('Roy Keane', 'premier-league'),
  ('Paul Scholes', 'premier-league'),
  ('Ryan Giggs', 'premier-league'),
  ('David Beckham', 'premier-league'),
  ('Gary Neville', 'premier-league'),
  ('Peter Schmeichel', 'premier-league'),
  ('Edwin van der Sar', 'premier-league'),
  ('Petr Cech', 'premier-league'),
  ('David Seaman', 'premier-league'),
  ('Tony Adams', 'premier-league'),
  ('Sol Campbell', 'premier-league'),
  ('Ashley Cole', 'premier-league'),
  ('Jamie Carragher', 'premier-league'),
  ('Xabi Alonso', 'premier-league'),
  ('Fernando Torres', 'premier-league'),
  ('Luis Suarez', 'premier-league'),
  ('Didier Drogba', 'premier-league'),
  ('Michael Essien', 'premier-league'),
  ('Claude Makelele', 'premier-league'),
  ('Cesc Fabregas', 'premier-league'),
  ('Robin van Persie', 'premier-league'),
  ('Sergio Aguero', 'premier-league'),
  ('Yaya Toure', 'premier-league'),
  ('Vincent Kompany', 'premier-league'),
  ('David Silva', 'premier-league'),
  ('Carlos Tevez', 'premier-league'),
  ('Gareth Bale', 'premier-league'),
  ('Luka Modric', 'premier-league'),
  ('Dimitar Berbatov', 'premier-league'),
  ('Nemanja Vidic', 'premier-league'),
  ('Mohamed Salah', 'premier-league'),
  ('Sadio Mane', 'premier-league'),
  ('Roberto Firmino', 'premier-league'),
  ('Virgil van Dijk', 'premier-league'),
  ('Trent Alexander-Arnold', 'premier-league'),
  ('Andrew Robertson', 'premier-league'),
  ('Alisson Becker', 'premier-league'),
  ('Jordan Henderson', 'premier-league'),
  ('Harry Kane', 'premier-league'),
  ('Son Heung-min', 'premier-league'),
  ('Hugo Lloris', 'premier-league'),
  ('Erling Haaland', 'premier-league'),
  ('Kevin De Bruyne', 'premier-league'),
  ('Phil Foden', 'premier-league'),
  ('Bernardo Silva', 'premier-league'),
  ('Rodri', 'premier-league'),
  ('Ruben Dias', 'premier-league'),
  ('Ederson', 'premier-league'),
  ('Jack Grealish', 'premier-league'),
  ('Bruno Fernandes', 'premier-league'),
  ('Marcus Rashford', 'premier-league'),
  ('Harry Maguire', 'premier-league'),
  ('David de Gea', 'premier-league'),
  ('Paul Pogba', 'premier-league'),
  ('Bukayo Saka', 'premier-league'),
  ('Martin Odegaard', 'premier-league'),
  ('Gabriel Martinelli', 'premier-league'),
  ('Gabriel Jesus', 'premier-league'),
  ('William Saliba', 'premier-league'),
  ('Declan Rice', 'premier-league'),
  ('Aaron Ramsdale', 'premier-league'),
  ('Cole Palmer', 'premier-league'),
  ('Enzo Fernandez', 'premier-league'),
  ('Mason Mount', 'premier-league'),
  ('N''Golo Kante', 'premier-league'),
  ('Eden Hazard', 'premier-league'),
  ('Diego Costa', 'premier-league'),
  ('Riyad Mahrez', 'premier-league'),
  ('Jamie Vardy', 'premier-league'),
  ('James Maddison', 'premier-league'),
  ('Wilfried Zaha', 'premier-league'),
  ('Christian Eriksen', 'premier-league'),
  ('Dele Alli', 'premier-league'),
  ('Joe Hart', 'premier-league'),
  ('Peter Crouch', 'premier-league'),
  ('Michael Owen', 'premier-league'),
  ('Alan Shearer', 'premier-league'),
  ('Andy Cole', 'premier-league'),
  ('Teddy Sheringham', 'premier-league'),
  ('Robbie Fowler', 'premier-league'),
  ('Ian Wright', 'premier-league'),
  ('Matt Le Tissier', 'premier-league'),
  ('Paul Gascoigne', 'premier-league'),
  ('Gianfranco Zola', 'premier-league'),
  ('Ruud van Nistelrooy', 'premier-league'),
  ('Park Ji-sung', 'premier-league'),
  ('Nicolas Anelka', 'premier-league'),
  ('Mesut Ozil', 'premier-league'),
  ('Alexis Sanchez', 'premier-league')
on conflict (name, category) do nothing;
