// Generate the Supabase migration that replaces the legacy football_players
// seed with the Wikidata-derived rich schema.
//
// Run: bun run scripts/seed-to-sql.ts
// Output: supabase/migrations/0010_replace_player_seed.sql
//
// Schema changes:
//   football_players  rebuilt: text PK (Wikidata QID), rich profile columns
//   player_clubs      new:     player→club association
//   categories        new:     query-driven category definitions
//   category_players  new:     resolved (category_slug, player_id) pairs
//   start_round       updated: joins through category_players

import { readFile, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
// scripts/ lives at apps/headball/scripts/ — workspace root is three levels up.
const ROOT = join(HERE, "..", "..", "..");
const SEED_DIR = join(ROOT, "data", "seed");
const MIGRATION_PATH = join(
  ROOT,
  "supabase",
  "migrations",
  "0010_replace_player_seed.sql",
);

// ---------- Types ----------

type Position = "GK" | "DEF" | "MID" | "FWD";
type Tier = 1 | 2 | 3 | 4;

type Player = {
  id: string;
  name: string;
  name_th: string | null;
  aliases: string[];
  nationalities: string[];
  birth_date: string | null;
  position: Position | null;
  clubs_named: string[];
  career_goals: number | null;
  sitelinks: number;
  difficulty_tier: Tier;
};

type Comparison = "eq" | "neq" | "gt" | "gte" | "lt" | "lte" | "contains" | "in";

type LeafQuery = { field: string; op: Comparison; value: unknown };
type Query =
  | LeafQuery
  | { all: Query[] }
  | { any: Query[] }
  | { not: Query };

type Category = {
  slug: string;
  label_en: string;
  label_th: string;
  query: Query;
};

type CategoriesFile = { version: number; categories: Category[] };

// ---------- Query DSL evaluator ----------

function evalQuery(q: Query, p: Player): boolean {
  if ("all" in q) return q.all.every((sub) => evalQuery(sub, p));
  if ("any" in q) return q.any.some((sub) => evalQuery(sub, p));
  if ("not" in q) return !evalQuery(q.not, p);

  const v = (p as unknown as Record<string, unknown>)[q.field];
  switch (q.op) {
    case "eq":
      return v === q.value;
    case "neq":
      return v !== q.value;
    case "contains":
      return Array.isArray(v) && v.includes(q.value);
    case "gt":
      return typeof v === "number" && v > (q.value as number);
    case "gte":
      return typeof v === "number" && v >= (q.value as number);
    case "lt":
      return typeof v === "number" && v < (q.value as number);
    case "lte":
      return typeof v === "number" && v <= (q.value as number);
    case "in":
      return Array.isArray(q.value) && (q.value as unknown[]).includes(v);
  }
}

// ---------- SQL escaping ----------

function sqlString(s: string | null): string {
  if (s === null) return "NULL";
  return `'${s.replace(/'/g, "''")}'`;
}

function sqlNumber(n: number | null): string {
  return n === null ? "NULL" : String(n);
}

function sqlTextArray(arr: string[]): string {
  if (arr.length === 0) return "ARRAY[]::text[]";
  const escaped = arr.map((s) => `'${s.replace(/'/g, "''")}'`).join(", ");
  return `ARRAY[${escaped}]`;
}

function sqlJsonb(value: unknown): string {
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
}

// ---------- SQL emission ----------

function emitSchema(): string {
  return `
-- 0010_replace_player_seed.sql
-- AUTO-GENERATED by scripts/seed-to-sql.ts. DO NOT EDIT BY HAND.
-- Re-run: bun run seed:sql && bunx supabase db reset

begin;

-- Drop the legacy flat football_players table. CASCADE removes the start_round
-- function so we can rebuild it against the new schema.
drop function if exists start_round(uuid, uuid) cascade;
drop table if exists football_players cascade;

-- ---------------------------------------------------------------------------
-- Rich football player profile keyed by Wikidata QID (e.g. 'Q10520').
-- ---------------------------------------------------------------------------
create table football_players (
  id              text primary key,
  name            text not null,
  name_th         text,
  aliases         text[] not null default '{}',
  nationalities   text[] not null default '{}',
  birth_date      date,
  position        text check (position in ('GK','DEF','MID','FWD')),
  career_goals    int,
  sitelinks       int not null default 0,
  difficulty_tier int not null check (difficulty_tier between 1 and 4)
);
create index football_players_tier_idx          on football_players (difficulty_tier);
create index football_players_nationalities_idx on football_players using gin (nationalities);

-- ---------------------------------------------------------------------------
-- Career club membership. One row per (player, club) pair.
-- ---------------------------------------------------------------------------
create table player_clubs (
  player_id text references football_players(id) on delete cascade,
  club_name text not null,
  primary key (player_id, club_name)
);
create index player_clubs_club_name_idx on player_clubs (club_name);

-- ---------------------------------------------------------------------------
-- Category definitions + their resolved player set.
-- The query DSL is stored as jsonb for future reference / admin tooling;
-- the authoritative resolved set lives in category_players.
-- ---------------------------------------------------------------------------
create table categories (
  slug     text primary key,
  label_en text not null,
  label_th text not null,
  query    jsonb not null
);

create table category_players (
  category_slug text references categories(slug) on delete cascade,
  player_id     text references football_players(id) on delete cascade,
  primary key (category_slug, player_id)
);
create index category_players_slug_idx on category_players (category_slug);

-- ---------------------------------------------------------------------------
-- start_round: pulls a category's player pool through category_players.
-- Same external interface as before; rooms.category is now a category slug.
-- ---------------------------------------------------------------------------
create or replace function start_round(
  p_room_id uuid,
  p_host_player_id uuid
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_host         uuid;
  v_round        int;
  v_category     text;
  v_player_count int;
  v_name_count   int;
begin
  -- Verify caller is the room host and pull the active round + category.
  select host_player_id, current_round, category
    into v_host, v_round, v_category
  from rooms where id = p_room_id;

  if v_host is null then
    raise exception 'room % not found', p_room_id;
  end if;
  if v_host <> p_host_player_id then
    raise exception 'only host can start a round';
  end if;

  select count(*) into v_player_count
  from players where room_id = p_room_id;
  if v_player_count = 0 then
    raise exception 'no players in room %', p_room_id;
  end if;

  select count(*) into v_name_count
  from category_players where category_slug = v_category;
  if v_name_count < v_player_count then
    raise exception 'not enough names in category % for % players', v_category, v_player_count;
  end if;

  insert into round_positions (room_id, round_number, next_position)
  values (p_room_id, v_round, 1)
  on conflict (room_id, round_number) do update set next_position = 1;

  with shuffled_players as (
    select player_id, row_number() over (order by random()) as rn
    from players where room_id = p_room_id
  ),
  shuffled_names as (
    select fp.name, row_number() over (order by random()) as rn
    from category_players cp
    join football_players fp on fp.id = cp.player_id
    where cp.category_slug = v_category
  )
  insert into round_state (room_id, round_number, player_id, assigned_name,
                           score_this_round, is_active, final_position)
  select p_room_id, v_round, sp.player_id, sn.name, 0, true, null
  from shuffled_players sp
  join shuffled_names sn on sn.rn = sp.rn
  on conflict (room_id, round_number, player_id) do update
    set assigned_name    = excluded.assigned_name,
        score_this_round = 0,
        is_active        = true,
        final_position   = null;
end;
$$;

-- RLS: anon role can SELECT every new lookup table (public lookup model).
alter table football_players  enable row level security;
alter table player_clubs      enable row level security;
alter table categories        enable row level security;
alter table category_players  enable row level security;

create policy football_players_anon_select on football_players  for select to anon using (true);
create policy player_clubs_anon_select     on player_clubs      for select to anon using (true);
create policy categories_anon_select       on categories        for select to anon using (true);
create policy category_players_anon_select on category_players  for select to anon using (true);
`;
}

function emitPlayerInserts(players: Player[]): string {
  const chunks: string[] = ["", "-- ===== football_players ====="];
  for (const p of players) {
    chunks.push(
      `insert into football_players (id, name, name_th, aliases, nationalities, birth_date, position, career_goals, sitelinks, difficulty_tier) values (` +
        [
          sqlString(p.id),
          sqlString(p.name),
          sqlString(p.name_th),
          sqlTextArray(p.aliases),
          sqlTextArray(p.nationalities),
          p.birth_date ? sqlString(p.birth_date) : "NULL",
          sqlString(p.position),
          sqlNumber(p.career_goals),
          sqlNumber(p.sitelinks),
          String(p.difficulty_tier),
        ].join(", ") +
        ");",
    );
  }
  return chunks.join("\n");
}

function emitClubInserts(players: Player[]): string {
  const chunks: string[] = ["", "-- ===== player_clubs ====="];
  for (const p of players) {
    for (const club of p.clubs_named) {
      chunks.push(
        `insert into player_clubs (player_id, club_name) values (${sqlString(p.id)}, ${sqlString(club)});`,
      );
    }
  }
  return chunks.join("\n");
}

function emitCategoryInserts(
  categories: Category[],
  resolvedSets: Map<string, string[]>,
): string {
  const chunks: string[] = ["", "-- ===== categories ====="];
  for (const c of categories) {
    chunks.push(
      `insert into categories (slug, label_en, label_th, query) values (${sqlString(c.slug)}, ${sqlString(c.label_en)}, ${sqlString(c.label_th)}, ${sqlJsonb(c.query)});`,
    );
  }
  chunks.push("", "-- ===== category_players (resolved from query DSL) =====");
  for (const c of categories) {
    const playerIds = resolvedSets.get(c.slug) ?? [];
    for (const pid of playerIds) {
      chunks.push(
        `insert into category_players (category_slug, player_id) values (${sqlString(c.slug)}, ${sqlString(pid)});`,
      );
    }
  }
  return chunks.join("\n");
}

// ---------- Main ----------

async function main(): Promise<void> {
  const players = JSON.parse(
    await readFile(join(SEED_DIR, "players.json"), "utf8"),
  ) as Player[];
  const categoriesFile = JSON.parse(
    await readFile(join(SEED_DIR, "categories.json"), "utf8"),
  ) as CategoriesFile;

  console.log(
    `Loaded ${players.length} players, ${categoriesFile.categories.length} categories`,
  );

  // Resolve each category's query → set of player IDs
  const resolved = new Map<string, string[]>();
  for (const cat of categoriesFile.categories) {
    const ids = players.filter((p) => evalQuery(cat.query, p)).map((p) => p.id);
    resolved.set(cat.slug, ids);
    console.log(`  ${cat.slug.padEnd(28)} ${String(ids.length).padStart(5)} players`);
  }

  // Always have a "premier-league" category to keep the existing
  // rooms.category default ('premier-league') working out of the box.
  // Mirrors the 20 current PL clubs in fetch-wikidata.ts CLUBS array.
  if (!resolved.has("premier-league")) {
    const plClubs = [
      "Liverpool F.C.",
      "Manchester United F.C.",
      "Arsenal F.C.",
      "Chelsea F.C.",
      "Manchester City F.C.",
      "Tottenham Hotspur F.C.",
      "AFC Bournemouth",
      "Aston Villa F.C.",
      "Brentford F.C.",
      "Brighton & Hove Albion F.C.",
      "Burnley F.C.",
      "Crystal Palace F.C.",
      "Everton F.C.",
      "Fulham F.C.",
      "Leeds United F.C.",
      "Newcastle United F.C.",
      "Nottingham Forest F.C.",
      "Sunderland A.F.C.",
      "West Ham United F.C.",
      "Wolverhampton Wanderers F.C.",
    ];
    const ids = players
      .filter((p) => p.clubs_named.some((c) => plClubs.includes(c)))
      .map((p) => p.id);
    resolved.set("premier-league", ids);
    categoriesFile.categories.push({
      slug: "premier-league",
      label_en: "Premier League (any 2025-26 club)",
      label_th: "พรีเมียร์ลีก",
      query: {
        any: plClubs.map((c) => ({ field: "clubs_named", op: "contains", value: c })),
      } as Query,
    });
    console.log(
      `  premier-league (auto-added)   ${String(ids.length).padStart(5)} players`,
    );
  }

  const sql =
    emitSchema() +
    emitPlayerInserts(players) +
    emitClubInserts(players) +
    emitCategoryInserts(categoriesFile.categories, resolved) +
    "\n\ncommit;\n";

  await writeFile(MIGRATION_PATH, sql);
  console.log(`\nWrote ${MIGRATION_PATH}`);
  console.log(`Migration size: ${(sql.length / 1024).toFixed(1)} KB`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
